---
title: "Fish_Farm_Location"
output: html_document
date: "2023-04-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE, echo=FALSE}
library(dplyr)
library(googleway)
library(maps)
library(ggplot2)
library(ggforce)
```

## Reef location
### select reef in Indonesia
```{r}
Indonesia_Reef <- read.csv("Reef_Check_with_cortad_variables_with_annual_rate_of_SST_change.csv")
Indonesia_Reef <- filter(Indonesia_Reef, Country == "Indonesia")
```

## select unique Indonesia reef location data
Since the original dataset have many year information for one reef, we need to select the unique location.
```{r}
unique_location <- Indonesia_Reef %>% distinct(Latitude.Degrees, Longitude.Degrees)
```

## fish location search by using google API
Finding fish farms located no more than 500 meters away from the reef
```{r}
# Replace 'your_gmaps_key' with your own Google Maps API key
gmaps_key <- 'your_gmaps_key'

# Set the search radius for fish farms (in meters)
radius <- 500

# Create an empty list to store the search results
fish_farms_list <- list()

# Loop through each row of the dataset
for (i in 1:nrow(unique_location)) {
  # Get the latitude and longitude for this row
  lat <- unique_location[i, "Latitude.Degrees"]
  lng <- unique_location[i, "Longitude.Degrees"]
  
  # Search for fish farms near this location
  fish_farms <- google_places(search_string = 'fish farm', 
                              location = c(lat, lng), 
                              radius = radius, 
                              key = gmaps_key)
  
  # Add the search results to the list
  fish_farms_list[[i]] <- fish_farms$results$geometry$location
  
}

# Combine all the search results into a single dataframe
fish_farms_df <- do.call(rbind, fish_farms_list)

```

## map for fish farms & reef
```{r}
# Define the world map plot with Indonesia boundaries
world_indonesia <- ggplot() +
  geom_polygon(data = world_map, aes(x = long, y = lat, group = group), 
               fill = "grey", alpha = 0.3) +
  geom_point(data = Indonesia_Reef, alpha = 0.2, aes(y = Latitude.Degrees, x = Longitude.Degrees,
                                                     size = Average_bleaching, color = Average_bleaching)) +
  labs(y = "Latitude", x = "Longitude", color = "average bleaching", size = "average bleaching") +
  theme_minimal() +
  coord_map(xlim = c(95, 145), ylim = c(-12, 7))

# Add the fish farms circles to the plot
world_indonesia +
  geom_circle(data = fish_farms_df, aes(x0 = lng, y0 = lat, r = 0.05), 
              fill = "red", alpha = 0.2, color = "red", inherit.aes = FALSE)

```

